captainVersion: 4
services:
    $$cap_appname:
        image: "photoprism/photoprism:$$app_version"
        depends_on:
            - $$cap_appname-db
        security_opt: "-seccomp:unconfined -apparmor:unconfined"
        environment:
            PHOTOPRISM_ADMIN_PASSWORD: $$app_admin_password
            PHOTOPRISM_AUTH_MODE: password
            PHOTOPRISM_SITE_URL: "https://$$cap_appname.$$cap_root_domain"
            PHOTOPRISM_ORIGINALS_LIMIT: $$app_upload_size_limit
            PHOTOPRISM_HTTP_COMPRESSION: gzip
            PHOTOPRISM_UPLOAD_NSFW: "true"
            PHOTOPRISM_DATABASE_DRIVER: mysql
            PHOTOPRISM_DATABASE_SERVER: srv-captain--$$cap_appname-db
            PHOTOPRISM_DATABASE_NAME: photoprism
            PHOTOPRISM_DATABASE_USER: photoprism
            PHOTOPRISM_DATABASE_PASSWORD: $$db_password
        volumes:
            - "$$cap_appname-originals:/photoprism/originals"
            - "$$cap_appname-storage:/photoprism/storage"
        working_dir: /photoprism
        caproverExtra:
            containerHttpPort: "2342"
    $$cap_appname-db:
        restart: unless-stopped
        image: "mariadb:$$db_version"
        security_opt:
            - "seccomp:unconfined"
            - apparmor: unconfined
        command: >-
            mysqld --innodb-buffer-pool-size=512M
            --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci --max-connections=512
            --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
            - "$$cap_appname-db:/var/lib/mysql"
        environment:
            MARIADB_AUTO_UPGRADE: "1"
            MARIADB_INTDB_SKIP_TZINFO: "1"
            MARIADB_DATABASE: photoprism
            MARIADB_USER: photoprism
            MARIADB_PASSWORD: $$db_password
            MARIADB_ROOT_PASSWORD: $$db_root_password
        caproverExtra:
            notExposeAsWebApp: "true"
caproverOneClickApp:
    variables:
        - id: $$app_version
          label: Photoprism Version
          defaultValue: latest
          description: >-
              Check out their Docker page for the valid tags
              https://hub.docker.com/r/photoprism/photoprism/tags
          validRegex: '/^([^\s^\/])+$/'
        - id: $$app_admin_password
          label: Photoprism Admin Password
          defaultValue: $$cap_gen_random_hex(32)
          description: Set a secure password for the admin user
          validRegex: "/.{1,}/"
        - id: $$app_upload_size_limit
          label: File Size Limit
          defaultValue: "5000"
          description: File Size Limit for Originals in MB
          validRegex: '/^([^\s^\/])+$/'
        - id: $$db_version
          label: Mariadb Version
          defaultValue: "10.9"
          description: >-
              Check out their Docker page for the valid tags
              https://hub.docker.com/_/mariadb/tags
          validRegex: '/^([^\s^\/])+$/'
        - id: $$db_password
          label: MariaDB User Password
          defaultValue: $$cap_gen_random_hex(32)
          description: User password for the database
          validRegex: "/.{1,}/"
        - id: $$db_root_password
          label: MariaDB Root Password
          defaultValue: $$cap_gen_random_hex(32)
          description: Root password for the database
          validRegex: "/.{1,}/"
    instructions:
        start: |-
            AI-Powered Photos App for the Decentralized Web
            More details: https://photoprism.app/
        end: >-
            Photoprism  has been successfully deployed! Important further steps: 1.
            Enable HTTPS on the domain. 2. Enable websocker support
    displayName: Photoprism (vbbot)
    isOfficial: true
    description: AI-Powered Photos App for the Decentralized Web
    documentation: "See https://photoprism.app/"
